name: Build Tools

on:
  push:
    branches: [ main, philip/github-workflow ]
  pull_request:
    branches: [ main, philip/github-workflow ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vulns

    steps:
    - uses: actions/checkout@v4
      with:
        path: vulns
        submodules: true # Initialize submodules
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgit2-dev just meson
    - name: Clone Linux Kernel
      run: |
        mkdir -p ~/.kernel
        git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git ~/.kernel
    - name: Set CVEKERNELTREE
      run: echo "CVEKERNELTREE=$HOME/.kernel" >> $GITHUB_ENV
    - name: Build and populate verhaal database
      run: |
        cd tools/verhaal
        just make
        just build_db
    - name: Build utils
      run: just build_utils
    - name: Run annual CVE summary
      run: just summary
    - name: Total vulnerable CVE's in 6.12.1
      run: ./scripts/strak v6.12.1
